// <auto-generated />
using System;
using GasTracker.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GasTracker.Migrations
{
    [DbContext(typeof(TrackerContext))]
    partial class TrackerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034");

            modelBuilder.Entity("GasTracker.Models.Trip", b =>
                {
                    b.Property<int>("TripId")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("CostPerGallon");

                    b.Property<decimal>("CostPerMile");

                    b.Property<DateTime>("Date");

                    b.Property<decimal>("MilesPerGallon");

                    b.Property<int>("Odometer");

                    b.Property<decimal>("TotalFuelCost");

                    b.Property<decimal>("TotalGallons");

                    b.Property<decimal>("TripMeter");

                    b.Property<int?>("VehicleId");

                    b.HasKey("TripId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("GasTracker.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Username");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GasTracker.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Make");

                    b.Property<string>("Model");

                    b.Property<int>("UserId");

                    b.Property<int>("Vin");

                    b.HasKey("VehicleId");

                    b.HasIndex("UserId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("GasTracker.Models.Trip", b =>
                {
                    b.HasOne("GasTracker.Models.Vehicle")
                        .WithMany("Trips")
                        .HasForeignKey("VehicleId");
                });

            modelBuilder.Entity("GasTracker.Models.Vehicle", b =>
                {
                    b.HasOne("GasTracker.Models.User", "User")
                        .WithMany("Vehicles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
